### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by sirugh** [sirugh/restorativebodywork.co#2]
- [x] set contact details
- [x] fill out FAQ
- [x] add services and pricing
- [x] add "about"
- [x] fix sitemap: https://restorativebodyworkatx.com/sitemap-0.xml
- [ ] improve image loading (rather than bg image, use src set, etc)
